/**
 * MIGRATION_REPORT.md generator (S5-5, ARCHITECTURE §7.3): the honest
 * companion to every converted project — coverage, punch list with
 * sourceRefs, the mandatory selector validation checklist, and a
 * deterministic effort estimate. The punch list IS the product framing:
 * assisted conversion with a clear statement of the remaining work.
 */
import type { ConversionIssue, ObjectConversion, ProcessConversion } from '@prismshift/transformer';

const EFFORT = {
  reviewMinutesPerStage: 3,
  minutesPerPunchItem: 30,
  minutesPerSelector: 10,
  extraMinutesPerRiskySelector: 20,
};

/**
 * Planning-effort estimate in hours (1 decimal) — the same formula the
 * report's effort table prints. Exported so metadata sync (S6-4) ships the
 * identical number the report shows.
 */
export function estimateEffortHours(
  processConversion: ProcessConversion,
  objectConversions: ObjectConversion[],
): number {
  const allPunch = [
    ...processConversion.punchList,
    ...objectConversions.flatMap((o) => o.punchList),
  ];
  const allSelectors = objectConversions.flatMap((o) => o.selectors);
  const riskySelectors = allSelectors.filter(
    (s) => s.strategy === 'image-ocr' || s.confidence < 0.5,
  );
  const totalStages =
    processConversion.totalStageCount +
    objectConversions.reduce((n, o) => n + o.totalStageCount, 0);
  const totalMinutes =
    totalStages * EFFORT.reviewMinutesPerStage +
    allPunch.length * EFFORT.minutesPerPunchItem +
    allSelectors.length * EFFORT.minutesPerSelector +
    riskySelectors.length * EFFORT.extraMinutesPerRiskySelector;
  return Math.round((totalMinutes / 60) * 10) / 10;
}

function punchTable(issues: ConversionIssue[]): string {
  if (issues.length === 0) return '_None — nothing needs manual work._\n';
  const rows = issues
    .map(
      (issue) =>
        `| ${issue.pageName} | ${issue.stageName} | \`${issue.stageKind}\` | ${issue.reason} | \`${issue.sourceRef}\` |`,
    )
    .join('\n');
  return `| Page | Stage | Kind | What to do | Source |\n|---|---|---|---|---|\n${rows}\n`;
}

export function buildMigrationReport(
  processConversion: ProcessConversion,
  objectConversions: ObjectConversion[],
): string {
  const lines: string[] = [];
  const push = (text = '') => lines.push(text);

  const allPunch = [
    ...processConversion.punchList,
    ...objectConversions.flatMap((o) => o.punchList),
  ];
  const allSelectors = objectConversions.flatMap((o) => o.selectors);
  const riskySelectors = allSelectors.filter(
    (s) => s.strategy === 'image-ocr' || s.confidence < 0.5,
  );
  const totalStages =
    processConversion.totalStageCount +
    objectConversions.reduce((n, o) => n + o.totalStageCount, 0);

  push(`# Migration Report — ${processConversion.processName}`);
  push();
  push(
    'Generated by PrismShift. This is an **assisted** conversion: the punch list below is the remaining manual work, and every generated selector must be validated against the live application before go-live.',
  );
  push();

  // --- Coverage ---
  push('## Conversion coverage');
  push();
  push('| Component | Stages converted | Coverage |');
  push('|---|---|---|');
  push(
    `| ${processConversion.processName} (process) | ${processConversion.convertedStageCount}/${processConversion.totalStageCount} | ${processConversion.coveragePct}% |`,
  );
  for (const object of objectConversions) {
    push(
      `| ${object.objectName} (object) | ${object.convertedStageCount}/${object.totalStageCount} | ${object.coveragePct}% |`,
    );
  }
  push();

  // --- Punch list ---
  push(`## Punch list (${allPunch.length} item${allPunch.length === 1 ? '' : 's'})`);
  push();
  push(punchTable(allPunch));

  // --- Selector checklist ---
  push(`## Selector validation checklist (${allSelectors.length} — ALL mandatory)`);
  push();
  if (allSelectors.length === 0) {
    push('_No application elements in scope._');
  } else {
    push('| Object | Element | Mode | Selector / strategy | Confidence | Notes |');
    push('|---|---|---|---|---|---|');
    for (const selector of allSelectors) {
      const target =
        selector.selector !== undefined ? `\`${selector.selector}\`` : '**Image/OCR required**';
      const notes = selector.notes.length > 0 ? selector.notes.join('; ') : '—';
      push(
        `| ${selector.objectName} | ${selector.elementName} | ${selector.mode} | ${target} | ${selector.confidence} | ${notes} |`,
      );
    }
  }
  push();
  push(
    '> Selectors are generated from App Modeller metadata and **cannot be verified without the live target applications**. Validate each one in UiPath Studio (UI Explorer) before relying on it.',
  );
  push();

  // --- Effort estimate ---
  const reviewMinutes = totalStages * EFFORT.reviewMinutesPerStage;
  const punchMinutes = allPunch.length * EFFORT.minutesPerPunchItem;
  const selectorMinutes =
    allSelectors.length * EFFORT.minutesPerSelector +
    riskySelectors.length * EFFORT.extraMinutesPerRiskySelector;
  const totalMinutes = reviewMinutes + punchMinutes + selectorMinutes;
  const hours = (minutes: number): string => (minutes / 60).toFixed(1);

  push('## Effort estimate');
  push();
  push('| Activity | Basis | Est. hours |');
  push('|---|---|---|');
  push(
    `| Review converted workflows | ${totalStages} stages × ${EFFORT.reviewMinutesPerStage} min | ${hours(reviewMinutes)} |`,
  );
  push(
    `| Resolve punch-list items | ${allPunch.length} × ${EFFORT.minutesPerPunchItem} min | ${hours(punchMinutes)} |`,
  );
  push(
    `| Validate selectors | ${allSelectors.length} × ${EFFORT.minutesPerSelector} min (+${EFFORT.extraMinutesPerRiskySelector} min for ${riskySelectors.length} risky) | ${hours(selectorMinutes)} |`,
  );
  push(`| **Total** | | **${hours(totalMinutes)}** |`);
  push();
  push(
    '_Estimates are heuristics for planning, not commitments. Risky selectors = image/OCR candidates or confidence < 0.5._',
  );
  push();

  return `${lines.join('\n')}\n`;
}
