import { XMLParser, XMLValidator } from 'fast-xml-parser';
import { describe, expect, it } from 'vitest';
import { emitWorkflowXaml, escapeXml } from './xaml';
import type { WorkflowDoc, XActivity } from './xaml';

/** A composite workflow exercising every emitter in the template layer. */
function compositeDoc(): WorkflowDoc {
  const processRow: XActivity = {
    kind: 'sequence',
    displayName: 'Process One Row',
    activities: [
      {
        kind: 'assign',
        displayName: 'Compute Total',
        to: 'Total',
        value: 'CurrentRow("Net").ToString + CurrentRow("Tax").ToString',
        type: 'String',
      },
      {
        kind: 'invokeWorkflow',
        displayName: 'Enter Invoice',
        workflowFile: 'Pages\\EnterInvoice.xaml',
        arguments: [
          { name: 'in_InvoiceRef', direction: 'in', type: 'String', expression: 'Total' },
          { name: 'out_Confirmed', direction: 'out', type: 'Boolean', expression: 'Confirmed' },
        ],
      },
    ],
  };

  return {
    className: 'MainPage',
    arguments: [
      { name: 'in_RunDate', direction: 'in', type: 'DateTime' },
      { name: 'out_TotalMetrics', direction: 'out', type: 'Double' },
      { name: 'io_Config', direction: 'inout', type: 'Object' },
    ],
    body: {
      kind: 'sequence',
      displayName: 'Main Page',
      variables: [
        { name: 'Total', type: 'String', defaultExpression: '""' },
        { name: 'Confirmed', type: 'Boolean' },
        { name: 'Invoices', type: 'DataTable' },
      ],
      activities: [
        { kind: 'comment', text: 'Generated by PrismShift from Blue Prism page "Main Page"' },
        {
          kind: 'tryCatch',
          displayName: 'Transaction Guard',
          tryBody: {
            kind: 'forEachRow',
            displayName: 'For Each Invoice',
            dataTable: 'Invoices',
            body: processRow,
          },
          catches: [
            {
              exceptionType: 'BusinessRuleException',
              body: { kind: 'writeLine', text: '"Business rule: " & exception.Message' },
            },
            { exceptionType: 'Exception' },
          ],
          finallyBody: { kind: 'writeLine', displayName: 'Log Done', text: '"finished"' },
        },
        {
          kind: 'if',
          displayName: 'Confirmed?',
          condition: 'Confirmed AndAlso Total <> ""',
          then: { kind: 'assign', to: 'out_TotalMetrics', value: 'CDbl(Total)', type: 'Double' },
          else: { kind: 'writeLine', text: '"not confirmed"' },
        },
      ],
    },
  };
}

describe('emitWorkflowXaml', () => {
  it('emits the composite workflow exactly (snapshot)', () => {
    expect(emitWorkflowXaml(compositeDoc())).toMatchSnapshot();
  });

  it('emits well-formed XML', () => {
    const xaml = emitWorkflowXaml(compositeDoc());
    expect(XMLValidator.validate(xaml)).toBe(true);
  });

  it('has the UiPath document shape: namespaces, members, expression settings', () => {
    const xaml = emitWorkflowXaml(compositeDoc());
    const doc = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '@_' }).parse(
      xaml,
    ) as Record<string, Record<string, unknown>>;

    const activity = doc['Activity']!;
    expect(activity['@_x:Class']).toBe('MainPage');
    expect(activity['@_xmlns']).toBe('http://schemas.microsoft.com/netfx/2009/xaml/activities');
    expect(activity['@_xmlns:ui']).toBe('http://schemas.uipath.com/workflow/activities');

    const members = activity['x:Members'] as { 'x:Property': { '@_Name': string; '@_Type': string }[] };
    expect(members['x:Property']).toHaveLength(3);
    expect(members['x:Property'][0]!).toMatchObject({
      '@_Name': 'in_RunDate',
      '@_Type': 'InArgument(s:DateTime)',
    });
    expect(members['x:Property'][1]!).toMatchObject({
      '@_Name': 'out_TotalMetrics',
      '@_Type': 'OutArgument(x:Double)',
    });
    expect(members['x:Property'][2]!).toMatchObject({
      '@_Name': 'io_Config',
      '@_Type': 'InOutArgument(x:Object)',
    });

    expect(activity['TextExpression.NamespacesForImplementation']).toBeDefined();
    expect(activity['TextExpression.ReferencesForImplementation']).toBeDefined();
  });

  it('wraps VB expressions in brackets and escapes XML metacharacters', () => {
    const xaml = emitWorkflowXaml({
      className: 'Escapes',
      arguments: [],
      body: {
        kind: 'sequence',
        activities: [
          {
            kind: 'assign',
            to: 'Message',
            value: '"a" & "<b>" & Chr(34)',
            type: 'String',
          },
        ],
      },
    });

    expect(XMLValidator.validate(xaml)).toBe(true);
    expect(xaml).toContain('[&quot;a&quot; &amp; &quot;&lt;b&gt;&quot; &amp; Chr(34)]');

    // Round-trip: the parsed value restores the original expression
    const doc = new XMLParser({ ignoreAttributes: false }).parse(xaml) as {
      Activity: {
        Sequence: { Assign: { 'Assign.Value': { InArgument: { '#text': string } } } };
      };
    };
    expect(doc.Activity.Sequence.Assign['Assign.Value'].InArgument['#text']).toBe(
      '["a" & "<b>" & Chr(34)]',
    );
  });

  it('nests variables on the owning sequence with defaults', () => {
    const xaml = emitWorkflowXaml(compositeDoc());
    expect(xaml).toContain(
      '<Variable x:TypeArguments="x:String" Default="[&quot;&quot;]" Name="Total" />',
    );
    expect(xaml).toContain('<Variable x:TypeArguments="x:Boolean" Name="Confirmed" />');
    expect(xaml).toContain('<Variable x:TypeArguments="sd:DataTable" Name="Invoices" />');
  });

  it('emits both exception catch types with delegate arguments', () => {
    const xaml = emitWorkflowXaml(compositeDoc());
    expect(xaml).toContain('<Catch x:TypeArguments="ui:BusinessRuleException">');
    expect(xaml).toContain('<Catch x:TypeArguments="s:Exception">');
    expect(xaml).toContain(
      '<DelegateInArgument x:TypeArguments="s:Exception" Name="exception" />',
    );
  });

  it('is deterministic', () => {
    expect(emitWorkflowXaml(compositeDoc())).toBe(emitWorkflowXaml(compositeDoc()));
  });
});

describe('escapeXml', () => {
  it('escapes all XML metacharacters', () => {
    expect(escapeXml('a & b < c > d " e')).toBe('a &amp; b &lt; c &gt; d &quot; e');
  });
});
